name: Luacheck

on:
  pull_request:
  push: 
    branches: 
      - master

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Luacheck
        uses: lunarmodules/luacheck@v1
        with:
          args: . --std max+busted
