on: ["push", "pull_request"]

name: Run Tests and Code Coverage

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_number:
          - lua=5.1
          - lua=5.2
          - lua=5.3
          - lua=5.4
          - luajit=2.0
          - luajit=2.1
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-python@v4

    - name: install lua and dependencies
      run: |
        pip install hererocks
        hererocks lua_install -r^ --${{ matrix.test_number }}
        export PATH=$PATH:$PWD/lua_install/bin
        luarocks install busted
        luarocks install lua-cjson
        luarocks install luacov
        luarocks install luacov-coveralls
        
    - name: run unit tests with coverage
      run: |
        busted --verbose --coverage
        
    - name: Report test coverage
      if: success()
      continue-on-error: true
      run: luacov-coveralls -i fluent -e .luarocks
      env:
        COVERALLS_REPO_TOKEN: ${{ github.token }}
